server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: my-very-secret-key-for-jwt-which-is-very-very-very-very-very-very-long-enough

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: GlobalFilter
              args:
                baseMessage: Global Filter
                preLogger: true
                postLogger: true
          routes:
            - id: user-auth
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/auth/login, /api/v1/auth/register
              filters:
                - RewritePath=/api/v1/(?<segment>.*), /$\{segment}
                - AddRequestHeader=X-API-VERSION, v1
            - id: user-common
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/welcome
              filters:
                - RewritePath=/api/v1/users/(?<segment>.*), /$\{segment}
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - RewritePath=/api/v1/users/(?<segment>.*), /$\{segment}
                - name: AuthorizationHeaderFilter